FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY 0K.dat /usr/share/nginx/html/0K.dat
COPY 1K.dat /usr/share/nginx/html/1K.dat
COPY 10K.dat /usr/share/nginx/html/10K.dat
COPY 100K.dat /usr/share/nginx/html/100K.dat